[2025-03-28T07:04:25.396+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-03-28T07:03:11.340976+00:00 [queued]>
[2025-03-28T07:04:25.405+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-03-28T07:03:11.340976+00:00 [queued]>
[2025-03-28T07:04:25.406+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-03-28T07:04:25.417+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_de_prueba> on 2025-03-28 07:03:11.340976+00:00
[2025-03-28T07:04:25.430+0000] {standard_task_runner.py:57} INFO - Started process 204 to run task
[2025-03-28T07:04:25.433+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_modelos_de_prueba', 'manual__2025-03-28T07:03:11.340976+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpyzunht8k']
[2025-03-28T07:04:25.436+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask training_modelos_de_prueba
[2025-03-28T07:04:25.485+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-03-28T07:03:11.340976+00:00 [running]> on host a4c5a6dc7128
[2025-03-28T07:04:25.561+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_modelos_de_prueba' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T07:03:11.340976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T07:03:11.340976+00:00'
[2025-03-28T07:04:28.657+0000] {logging_mixin.py:149} WARNING - 2025/03/28 07:04:28 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-03-28T07:04:28.713+0000] {logging_mixin.py:149} WARNING - 2025/03/28 07:04:28 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-03-28T07:04:28.772+0000] {logging_mixin.py:149} WARNING - 2025/03/28 07:04:28 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/mlflow/utils/autologging_utils/safety.py:532: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel()."
[2025-03-28T07:04:36.628+0000] {logging_mixin.py:149} WARNING - 2025/03/28 07:04:36 WARNING mlflow.sklearn.utils: roc_auc_score failed. The metric training_roc_auc will not be recorded. Metric error: too many indices for array: array is 2-dimensional, but 3 were indexed
[2025-03-28T07:04:37.065+0000] {font_manager.py:1584} INFO - generated new fontManager
[2025-03-28T07:04:38.286+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-03-28T07:04:42.413+0000] {logging_mixin.py:149} WARNING - 2025/03/28 07:04:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-03-28T07:04:42.923+0000] {logging_mixin.py:149} WARNING - 2025/03/28 07:04:42 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-03-28T07:04:42.961+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[2025-03-28T07:05:06.602+0000] {logging_mixin.py:149} WARNING - 2025/03/28 07:05:06 WARNING mlflow.sklearn.utils: roc_auc_score failed. The metric training_roc_auc will not be recorded. Metric error: too many indices for array: array is 2-dimensional, but 3 were indexed
[2025-03-28T07:05:10.160+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-28T07:05:10.173+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_modelos_de_prueba, execution_date=20250328T070311, start_date=20250328T070425, end_date=20250328T070510
[2025-03-28T07:05:10.264+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-28T07:05:10.280+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
