[2025-05-02T02:34:43.889+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-05-02T02:33:48.627202+00:00 [queued]>
[2025-05-02T02:34:43.904+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-05-02T02:33:48.627202+00:00 [queued]>
[2025-05-02T02:34:43.904+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-05-02T02:34:43.924+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_with_gradient_boosting_model> on 2025-05-02 02:33:48.627202+00:00
[2025-05-02T02:34:43.952+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2025-05-02T02:34:43.968+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_with_gradient_boosting_model', 'manual__2025-05-02T02:33:48.627202+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpiz99v7kd']
[2025-05-02T02:34:43.974+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask training_with_gradient_boosting_model
[2025-05-02T02:34:44.106+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-05-02T02:33:48.627202+00:00 [running]> on host 5b68dcb6aec6
[2025-05-02T02:34:44.328+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_with_gradient_boosting_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T02:33:48.627202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T02:33:48.627202+00:00'
[2025-05-02T02:34:49.887+0000] {logging_mixin.py:149} WARNING - 2025/05/02 02:34:49 INFO mlflow.tracking.fluent: Experiment with name 'Gradient_Boosting_looking_for_the_best_model' does not exist. Creating a new experiment.
[2025-05-02T02:34:50.728+0000] {logging_mixin.py:149} WARNING - 2025/05/02 02:34:50 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-05-02T02:34:50.871+0000] {logging_mixin.py:149} WARNING - 2025/05/02 02:34:50 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-02T02:34:52.627+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2025-05-02T02:51:43.689+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-05-02T02:51:44.989+0000] {logging_mixin.py:149} WARNING - 2025/05/02 02:51:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/mlflow/models/signature.py:137: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-05-02T02:51:49.853+0000] {logging_mixin.py:149} WARNING - 2025/05/02 02:51:49 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-05-02T02:51:53.512+0000] {logging_mixin.py:149} WARNING - 2025/05/02 02:51:53 INFO mlflow.sklearn.utils: Logging the 5 best runs, 11 runs will be omitted.
[2025-05-02T02:51:53.830+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-02T02:51:53.856+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_with_gradient_boosting_model, execution_date=20250502T023348, start_date=20250502T023443, end_date=20250502T025153
[2025-05-02T02:51:53.920+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-02T02:51:53.966+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
