[2025-03-28T08:40:28.719+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-03-28T08:39:14.545503+00:00 [queued]>
[2025-03-28T08:40:28.729+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-03-28T08:39:14.545503+00:00 [queued]>
[2025-03-28T08:40:28.729+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-03-28T08:40:28.741+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_de_prueba> on 2025-03-28 08:39:14.545503+00:00
[2025-03-28T08:40:28.755+0000] {standard_task_runner.py:57} INFO - Started process 149 to run task
[2025-03-28T08:40:28.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_modelos_de_prueba', 'manual__2025-03-28T08:39:14.545503+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpjl6p2m9d']
[2025-03-28T08:40:28.762+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask training_modelos_de_prueba
[2025-03-28T08:40:28.810+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-03-28T08:39:14.545503+00:00 [running]> on host 264ebbec6e80
[2025-03-28T08:40:28.893+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_modelos_de_prueba' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T08:39:14.545503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T08:39:14.545503+00:00'
[2025-03-28T08:40:31.927+0000] {logging_mixin.py:149} WARNING - 2025/03/28 08:40:31 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-03-28T08:40:31.987+0000] {logging_mixin.py:149} WARNING - 2025/03/28 08:40:31 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-03-28T08:40:32.039+0000] {logging_mixin.py:149} WARNING - 2025/03/28 08:40:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/mlflow/utils/autologging_utils/safety.py:532: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel()."
[2025-03-28T08:40:40.047+0000] {logging_mixin.py:149} WARNING - 2025/03/28 08:40:40 WARNING mlflow.sklearn.utils: roc_auc_score failed. The metric training_roc_auc will not be recorded. Metric error: too many indices for array: array is 2-dimensional, but 3 were indexed
[2025-03-28T08:40:40.515+0000] {font_manager.py:1584} INFO - generated new fontManager
[2025-03-28T08:40:41.695+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-03-28T08:40:45.808+0000] {logging_mixin.py:149} WARNING - 2025/03/28 08:40:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-03-28T08:40:46.287+0000] {logging_mixin.py:149} WARNING - 2025/03/28 08:40:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-03-28T08:40:46.324+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[2025-03-28T08:41:09.821+0000] {logging_mixin.py:149} WARNING - 2025/03/28 08:41:09 WARNING mlflow.sklearn.utils: roc_auc_score failed. The metric training_roc_auc will not be recorded. Metric error: too many indices for array: array is 2-dimensional, but 3 were indexed
[2025-03-28T08:41:13.346+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-28T08:41:13.360+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_modelos_de_prueba, execution_date=20250328T083914, start_date=20250328T084028, end_date=20250328T084113
[2025-03-28T08:41:13.441+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-28T08:41:13.458+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
