[2025-04-03T03:30:16.597+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-04-03T03:28:58.771002+00:00 [queued]>
[2025-04-03T03:30:16.608+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-04-03T03:28:58.771002+00:00 [queued]>
[2025-04-03T03:30:16.608+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-04-03T03:30:16.620+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_de_prueba> on 2025-04-03 03:28:58.771002+00:00
[2025-04-03T03:30:16.633+0000] {standard_task_runner.py:57} INFO - Started process 205 to run task
[2025-04-03T03:30:16.639+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_modelos_de_prueba', 'manual__2025-04-03T03:28:58.771002+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpp9j344w1']
[2025-04-03T03:30:16.643+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask training_modelos_de_prueba
[2025-04-03T03:30:16.697+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-04-03T03:28:58.771002+00:00 [running]> on host 6de03e52d633
[2025-04-03T03:30:16.787+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_modelos_de_prueba' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T03:28:58.771002+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T03:28:58.771002+00:00'
[2025-04-03T03:30:19.072+0000] {logging_mixin.py:149} WARNING - 2025/04/03 03:30:19 INFO mlflow.tracking.fluent: Experiment with name 'mlflow_tracking_tipo_de_cubierta_forestal_proofs' does not exist. Creating a new experiment.
[2025-04-03T03:30:19.295+0000] {logging_mixin.py:149} WARNING - 2025/04/03 03:30:19 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-04-03T03:30:19.372+0000] {logging_mixin.py:149} WARNING - 2025/04/03 03:30:19 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-04-03T03:30:29.209+0000] {font_manager.py:1584} INFO - generated new fontManager
[2025-04-03T03:30:30.750+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-04-03T03:30:36.744+0000] {logging_mixin.py:149} WARNING - 2025/04/03 03:30:36 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-04-03T03:30:37.401+0000] {logging_mixin.py:149} WARNING - 2025/04/03 03:30:37 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-04-03T03:31:09.609+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-04-03T03:31:09.625+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_modelos_de_prueba, execution_date=20250403T032858, start_date=20250403T033016, end_date=20250403T033109
[2025-04-03T03:31:09.740+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-04-03T03:31:09.765+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
