[2025-03-28T05:10:55.548+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.truncate_all_tables manual__2025-03-28T05:10:52.108049+00:00 [queued]>
[2025-03-28T05:10:55.556+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.truncate_all_tables manual__2025-03-28T05:10:52.108049+00:00 [queued]>
[2025-03-28T05:10:55.556+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-03-28T05:10:55.571+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): truncate_all_tables> on 2025-03-28 05:10:52.108049+00:00
[2025-03-28T05:10:55.586+0000] {standard_task_runner.py:57} INFO - Started process 121 to run task
[2025-03-28T05:10:55.591+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'truncate_all_tables', 'manual__2025-03-28T05:10:52.108049+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpqg5iz25h']
[2025-03-28T05:10:55.595+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask truncate_all_tables
[2025-03-28T05:10:55.658+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.truncate_all_tables manual__2025-03-28T05:10:52.108049+00:00 [running]> on host 108217bbdaf4
[2025-03-28T05:10:55.751+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='truncate_all_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T05:10:52.108049+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T05:10:52.108049+00:00'
[2025-03-28T05:10:55.755+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-proyecto2.py", line 21, in truncate_all_tables
    engine = sqlalchemy.create_engine("mysql+pymysql://user:password@db-data:3307/db")
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 80, in dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
[2025-03-28T05:10:55.766+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=Pipeline-proyecto2, task_id=truncate_all_tables, execution_date=20250328T051052, start_date=20250328T051055, end_date=20250328T051055
[2025-03-28T05:10:55.782+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task truncate_all_tables (No module named 'pymysql'; 121)
[2025-03-28T05:10:55.806+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-28T05:10:55.826+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
