[2025-05-05T10:08:02.854+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-05-05T10:06:17.235188+00:00 [queued]>
[2025-05-05T10:08:02.888+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-05-05T10:06:17.235188+00:00 [queued]>
[2025-05-05T10:08:02.907+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-05-05T10:08:02.955+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_de_prueba> on 2025-05-05 10:06:17.235188+00:00
[2025-05-05T10:08:02.970+0000] {standard_task_runner.py:57} INFO - Started process 127 to run task
[2025-05-05T10:08:02.984+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_modelos_de_prueba', 'manual__2025-05-05T10:06:17.235188+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpjenevsiq']
[2025-05-05T10:08:03.008+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask training_modelos_de_prueba
[2025-05-05T10:08:03.339+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_modelos_de_prueba manual__2025-05-05T10:06:17.235188+00:00 [running]> on host 3ffd6f9b5180
[2025-05-05T10:08:03.640+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_modelos_de_prueba' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T10:06:17.235188+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T10:06:17.235188+00:00'
[2025-05-05T10:08:09.005+0000] {logging_mixin.py:149} WARNING - 2025/05/05 10:08:09 INFO mlflow.tracking.fluent: Experiment with name 'mlflow_tracking_tipo_de_cubierta_forestal_proofs' does not exist. Creating a new experiment.
[2025-05-05T10:08:16.255+0000] {logging_mixin.py:149} WARNING - 2025/05/05 10:08:16 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-05-05T10:08:17.337+0000] {logging_mixin.py:149} WARNING - 2025/05/05 10:08:17 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-05T10:08:54.751+0000] {font_manager.py:1040} WARNING - Matplotlib is building the font cache; this may take a moment.
[2025-05-05T10:08:58.254+0000] {font_manager.py:1584} INFO - generated new fontManager
[2025-05-05T10:09:14.735+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-05-05T10:10:08.233+0000] {logging_mixin.py:149} WARNING - 2025/05/05 10:10:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/mlflow/models/signature.py:137: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-05-05T10:11:30.150+0000] {logging_mixin.py:149} WARNING - 2025/05/05 10:11:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-05-05T10:12:00.548+0000] {logging_mixin.py:149} WARNING - 2025/05/05 10:12:00 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-05-05T10:12:42.690+0000] {logging_mixin.py:149} WARNING - 2025/05/05 10:12:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/mlflow/models/signature.py:137: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-05-05T10:13:01.679+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-05T10:13:01.726+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_modelos_de_prueba, execution_date=20250505T100617, start_date=20250505T100802, end_date=20250505T101301
[2025-05-05T10:13:01.905+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-05-05T10:13:01.962+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
