[2025-06-02T22:03:22.388+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-02T22:02:21.828324+00:00 [queued]>
[2025-06-02T22:03:22.403+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-02T22:02:21.828324+00:00 [queued]>
[2025-06-02T22:03:22.403+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-02T22:03:22.424+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_y_validacion> on 2025-06-02 22:02:21.828324+00:00
[2025-06-02T22:03:22.454+0000] {standard_task_runner.py:57} INFO - Started process 338 to run task
[2025-06-02T22:03:22.470+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto-final', 'training_modelos_y_validacion', 'manual__2025-06-02T22:02:21.828324+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto-final.py', '--cfg-path', '/tmp/tmpq9_8rzaf']
[2025-06-02T22:03:22.480+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask training_modelos_y_validacion
[2025-06-02T22:03:22.633+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-02T22:02:21.828324+00:00 [running]> on host 1aa9775b6819
[2025-06-02T22:03:22.971+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto-final' AIRFLOW_CTX_TASK_ID='training_modelos_y_validacion' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T22:02:21.828324+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T22:02:21.828324+00:00'
[2025-06-02T22:03:31.970+0000] {logging_mixin.py:149} INFO - 0.015208354417341169
[2025-06-02T22:03:31.993+0000] {logging_mixin.py:149} INFO - 0.6698276246637168
[2025-06-02T22:03:31.993+0000] {logging_mixin.py:149} INFO - Data drift en 'bed' con distancia Wasserstein = 0.6698
[2025-06-02T22:03:32.014+0000] {logging_mixin.py:149} INFO - 0.6734731477606025
[2025-06-02T22:03:32.014+0000] {logging_mixin.py:149} INFO - Data drift en 'bath' con distancia Wasserstein = 0.6735
[2025-06-02T22:03:32.042+0000] {logging_mixin.py:149} INFO - 0.009688305042472572
[2025-06-02T22:03:32.086+0000] {logging_mixin.py:149} INFO - 0.10859994231356597
[2025-06-02T22:03:32.087+0000] {logging_mixin.py:149} INFO - Data drift en 'house_size' con distancia Wasserstein = 0.1086
[2025-06-02T22:03:32.624+0000] {logging_mixin.py:149} WARNING - 2025/06/02 22:03:32 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-06-02T22:03:33.144+0000] {logging_mixin.py:149} WARNING - 2025/06/02 22:03:33 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-02T22:03:33.742+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-06-02T22:03:33.988+0000] {logging_mixin.py:149} WARNING - 2025/06/02 22:03:33 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/mlflow/models/signature.py:137: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[2025-06-02T22:03:40.270+0000] {logging_mixin.py:149} WARNING - 2025/06/02 22:03:40 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-06-02T22:03:41.093+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

[2025-06-02T22:03:41.150+0000] {logging_mixin.py:149} WARNING - Registered model 'Regresion_Lineal_modelo_produccion' already exists. Creating a new version of this model...
[2025-06-02T22:03:41.264+0000] {logging_mixin.py:149} WARNING - 2025/06/02 22:03:41 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: Regresion_Lineal_modelo_produccion, version 3
[2025-06-02T22:03:41.265+0000] {logging_mixin.py:149} WARNING - Created version '3' of model 'Regresion_Lineal_modelo_produccion'.
[2025-06-02T22:03:41.415+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-02T22:03:41.440+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto-final, task_id=training_modelos_y_validacion, execution_date=20250602T220221, start_date=20250602T220322, end_date=20250602T220341
[2025-06-02T22:03:41.552+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-02T22:03:41.598+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
