[2025-06-03T00:09:51.326+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-03T00:07:45.679410+00:00 [queued]>
[2025-06-03T00:09:51.351+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-03T00:07:45.679410+00:00 [queued]>
[2025-06-03T00:09:51.352+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-06-03T00:09:51.373+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_modelos_y_validacion> on 2025-06-03 00:07:45.679410+00:00
[2025-06-03T00:09:51.392+0000] {standard_task_runner.py:57} INFO - Started process 764 to run task
[2025-06-03T00:09:51.401+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto-final', 'training_modelos_y_validacion', 'manual__2025-06-03T00:07:45.679410+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto-final.py', '--cfg-path', '/tmp/tmpl9fls9cx']
[2025-06-03T00:09:51.407+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask training_modelos_y_validacion
[2025-06-03T00:09:51.505+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto-final.training_modelos_y_validacion manual__2025-06-03T00:07:45.679410+00:00 [running]> on host fe73afd4d10b
[2025-06-03T00:09:51.679+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto-final' AIRFLOW_CTX_TASK_ID='training_modelos_y_validacion' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T00:07:45.679410+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T00:07:45.679410+00:00'
[2025-06-03T00:10:20.496+0000] {logging_mixin.py:149} INFO - 0.03398580784859419
[2025-06-03T00:10:20.599+0000] {logging_mixin.py:149} INFO - 0.42180200733680373
[2025-06-03T00:10:20.600+0000] {logging_mixin.py:149} INFO - Data drift en 'bed' con distancia Wasserstein = 0.4218
[2025-06-03T00:10:20.704+0000] {logging_mixin.py:149} INFO - 0.7110692134838499
[2025-06-03T00:10:20.704+0000] {logging_mixin.py:149} INFO - Data drift en 'bath' con distancia Wasserstein = 0.7111
[2025-06-03T00:10:20.844+0000] {logging_mixin.py:149} INFO - 0.005934530433407879
[2025-06-03T00:10:21.012+0000] {logging_mixin.py:149} INFO - 0.1288599759783197
[2025-06-03T00:10:21.013+0000] {logging_mixin.py:149} INFO - Data drift en 'house_size' con distancia Wasserstein = 0.1289
[2025-06-03T00:10:21.879+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:10:21 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-06-03T00:10:22.074+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:10:22 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-03T00:10:22.731+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-06-03T00:10:29.615+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:10:29 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-06-03T00:10:30.690+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

[2025-06-03T00:10:30.756+0000] {logging_mixin.py:149} WARNING - Registered model 'Regresion_Lineal_modelo_produccion' already exists. Creating a new version of this model...
[2025-06-03T00:10:30.844+0000] {logging_mixin.py:149} WARNING - 2025/06/03 00:10:30 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: Regresion_Lineal_modelo_produccion, version 8
[2025-06-03T00:10:30.845+0000] {logging_mixin.py:149} WARNING - Created version '8' of model 'Regresion_Lineal_modelo_produccion'.
[2025-06-03T00:10:30.931+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-03T00:10:30.953+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto-final, task_id=training_modelos_y_validacion, execution_date=20250603T000745, start_date=20250603T000951, end_date=20250603T001030
[2025-06-03T00:10:31.026+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-06-03T00:10:31.066+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
