[2025-03-28T17:42:44.813+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-03-28T17:41:24.726209+00:00 [queued]>
[2025-03-28T17:42:44.826+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-03-28T17:41:24.726209+00:00 [queued]>
[2025-03-28T17:42:44.826+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-03-28T17:42:44.842+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): training_with_gradient_boosting_model> on 2025-03-28 17:41:24.726209+00:00
[2025-03-28T17:42:44.856+0000] {standard_task_runner.py:57} INFO - Started process 122 to run task
[2025-03-28T17:42:44.861+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Pipeline-proyecto2', 'training_with_gradient_boosting_model', 'manual__2025-03-28T17:41:24.726209+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/dag-proyecto2.py', '--cfg-path', '/tmp/tmpcs8u819b']
[2025-03-28T17:42:44.864+0000] {standard_task_runner.py:85} INFO - Job 121: Subtask training_with_gradient_boosting_model
[2025-03-28T17:42:44.929+0000] {task_command.py:410} INFO - Running <TaskInstance: Pipeline-proyecto2.training_with_gradient_boosting_model manual__2025-03-28T17:41:24.726209+00:00 [running]> on host 0873b231ce57
[2025-03-28T17:42:45.034+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline-proyecto2' AIRFLOW_CTX_TASK_ID='training_with_gradient_boosting_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T17:41:24.726209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T17:41:24.726209+00:00'
[2025-03-28T17:42:47.792+0000] {logging_mixin.py:149} WARNING - 2025/03/28 17:42:47 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[2025-03-28T17:42:47.868+0000] {logging_mixin.py:149} WARNING - 2025/03/28 17:42:47 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-03-28T17:42:48.642+0000] {logging_and_warnings.py:72} WARNING - /home/***/.local/lib/python3.9/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2025-03-28T20:44:00.963+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-03-28T20:44:04.212+0000] {logging_mixin.py:149} WARNING - 2025/03/28 20:44:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/***/.local/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."
[2025-03-28T20:44:06.444+0000] {logging_mixin.py:149} WARNING - 2025/03/28 20:44:06 INFO mlflow.sklearn.utils: Logging the 5 best runs, 31 runs will be omitted.
[2025-03-28T20:44:06.656+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-28T20:44:06.666+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=Pipeline-proyecto2, task_id=training_with_gradient_boosting_model, execution_date=20250328T174124, start_date=20250328T174244, end_date=20250328T204406
[2025-03-28T20:44:06.730+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-28T20:44:06.748+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
